# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test6' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test6' do
    @driver.get('http://localhost:3000/')
    sleep(1)
    @driver.find_element(:link_text, 'Войти').click
    sleep(1)
    @driver.find_element(:id, 'session_email').click
    @driver.find_element(:id, 'session_email').send_keys('2@gmail.com')
    @driver.find_element(:id, 'session_password').click
    @driver.find_element(:id, 'session_password').send_keys('1234')
    @driver.find_element(:name, 'commit').click
    sleep(1)
    @driver.find_element(:link_text, '1').click
    sleep(1)
    @driver.find_element(:link_text, 'Профили').click
    sleep(1)
    @driver.find_element(:css, '.card:nth-child(4) .btn').click
    sleep(1)
    expect(@driver.find_element(:css, '.btn:nth-child(10)').text).to eq('Редактировать профиль')
    @driver.find_element(:css, 'p:nth-child(5)').click
    @driver.find_element(:link_text, 'Выйти').click
  end
end
