# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test2' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test2' do
    @driver.get('http://localhost:3000/')
    sleep(1)
    @driver.find_element(:css, '.card:nth-child(2) img').click
    sleep(1)
    expect(@driver.find_element(:link_text, 'Зарегистрируйтесь, чтобы оставить комментарий').text).to eq('Зарегистрируйтесь, чтобы оставить комментарий')
  end
end
