# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test1' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test1' do
    @driver.get('http://localhost:3000/')
    sleep(1)
    @driver.find_element(:link_text, 'Войти').click
    sleep(1)
    @driver.find_element(:id, 'session_email').click
    @driver.find_element(:id, 'session_email').send_keys('1@gmail.com')
    @driver.find_element(:id, 'session_password').click
    @driver.find_element(:id, 'session_password').send_keys('1234')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, '1').click
    expect(@driver.find_element(:link_text, '1').text).to eq('1')
    @driver.find_element(:link_text, 'Выйти').click
  end
end
