# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test5' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test5' do
    @driver.get('http://localhost:3000/')
    sleep(1)
    @driver.find_element(:link_text, 'Войти').click
    sleep(1)
    @driver.find_element(:id, 'session_email').click
    @driver.find_element(:css, '.container:nth-child(4)').click
    @driver.find_element(:id, 'session_email').send_keys('admin@gmail.com')
    @driver.find_element(:id, 'session_password').click
    @driver.find_element(:id, 'session_password').send_keys('admin')
    @driver.find_element(:name, 'commit').click
    sleep(2)
    expect(@driver.find_element(:link_text, 'MSG').text).to eq('MSG')
    @driver.find_element(:css, '.container').click
    @driver.find_element(:link_text, 'Выйти').click
  end
end
